namespace GuideMe.Models
{
    public enum PlacesTypes
    {
        Airport,
        Amusement_park,
        Aquarium,
        Art_Gallery,
        Bar,
        Book_Store,
        Bowling_Alley,
        Cafe,
        Casino,
        cemetery,
        Church,
        City_hall,
        Clothing_store,
        Convenience_store,
        Courthouse,
        Embassy,
        Hindu_Temple,
        Mosque,
        Museum,
        Painter,
        Park,
        Stadium,
        Zoo
    }
}
